---
- name: create system user
  user:
    name: tomcat
    createhome: no
    home: /usr/local/tomcat
  become: yes
  become_user: root

- name: download tomcat archive
  get_url:
    url: http://ftp.jaist.ac.jp/pub/apache/tomcat/tomcat-8/v8.0.32/bin/apache-tomcat-8.0.32.tar.gz
    dest: /usr/local/apache-tomcat-8.0.32.tar.gz
    checksum: sha1:d063269b5fe67c312f8b50106d94aa8d80505582
  become: yes
  become_user: root

- name: unarchive tomcat
  unarchive:
    src: /usr/local/apache-tomcat-8.0.32.tar.gz
    dest: /usr/local/apache-tomcat-8.0.32
    owner: tomcat
  become: yes
  become_user: root
 
- name: create symlink
  file:
    src: /usr/local/apache-tomcat-8.0.32
    dest: /usr/local/tomcat
    state: link
  become: yes
  become_user: root

# - name: configure tomcat TODO 

# - name: create tomcat.service unit file TODO 

# - name: register service TODO 

